---
# we aren't using release-it for versioning, so git is "disabled" (commit, tag, push, etc. = false)
# it is needed here to set pushRepo to upstream as it defaults to origin if using --no-git option
git:
  changelog: false
  requireCleanWorkingDir: false
  commit: false
  tag: false
  push: false
  pushRepo: upstream
github:
  release: true
  releaseName: v${version}
  preRelease: true
  tokenRef: GH_TOKEN
  assets:
    - smartthings-*.zip
