import { type ArgumentsCamelCase, type Argv, type CommandModule } from 'yargs'

import {
	apiOrganizationCommand,
	apiOrganizationCommandBuilder,
	type APIOrganizationCommandFlags,
} from '../../lib/command/api-organization-command.js'
import { buildEpilog } from '../../lib/help.js'
import { outputItem, outputItemBuilder, type OutputItemFlags } from '../../lib/command/output-item.js'
import { chooseSmartAppFn } from '../../lib/command/util/smartapps-choose.js'
import { oauthTableFieldDefinitions } from '../../lib/command/util/smartapps-table.js'


export type CommandArgs =
	& APIOrganizationCommandFlags
	& OutputItemFlags
	& {
		idOrIndex?: string
	}

const command = 'smartapps:oauth [id-or-index]'

const describe = 'get OAuth information for a Smart App'

const builder = (yargs: Argv): Argv<CommandArgs> =>
	outputItemBuilder(apiOrganizationCommandBuilder(yargs))
		.positional('id-or-index', { describe: 'the Smart App id or number from list', type: 'string' })
		.example([
			['$0 smartapps:oauth', 'prompt for a Smart App and list OAuth information for it'],
			[
				'$0 smartapps:oauth 2',
				'list OAuth information for the second Smart App in the list generated by "smartthings smartapps"',
			],
			[
				'$0 smartapps:oauth 392bcb11-e251-44f3-b58b-17f93015f3aa',
				'list OAuth information for the Smart App with the given id',
			],
		])
		.epilog(buildEpilog({ command, apiDocs: 'getSmartAppOauth' }))

const handler = async (argv: ArgumentsCamelCase<CommandArgs>): Promise<void> => {
	const command = await apiOrganizationCommand(argv)

	const id = await chooseSmartAppFn({ accountId: command.client.config.headers?.['X-ST-Organization'] })(
		command, argv.idOrIndex, { allowIndex: true },
	)
	await outputItem(
		command,
		{ tableFieldDefinitions: oauthTableFieldDefinitions },
		() => command.client.smartapps.getOauth(id),
	)
}

const cmd: CommandModule<object, CommandArgs> = { command, describe, builder, handler }
export default cmd
