import { type ArgumentsCamelCase, type Argv, type CommandModule } from 'yargs'

import {
	apiOrganizationCommand,
	apiOrganizationCommandBuilder,
	type APIOrganizationCommandFlags,
} from '../../lib/command/api-organization-command.js'
import { buildEpilog } from '../../lib/help.js'
import { outputItem, outputItemBuilder, OutputItemFlags } from '../../lib/command/output-item.js'
import { chooseSmartAppFn } from '../../lib/command/util/smartapps-choose.js'
import { buildTableOutput } from '../../lib/command/util/smartapps-table.js'


export type CommandArgs =
	& APIOrganizationCommandFlags
	& OutputItemFlags
	& {
		idOrIndex?: string
	}

const command = 'smartapps:settings [id-or-index]'

const describe = 'get the settings of a Smart App'

const builder = (yargs: Argv): Argv<CommandArgs> =>
	outputItemBuilder(apiOrganizationCommandBuilder(yargs))
		.positional('id-or-index', { describe: 'the Smart App id or number from list', type: 'string' })
		.example([
			['$0 smartapps:settings', 'prompt for a Smart App and get settings for it'],
			[
				'$0 smartapps:settings 3',
				'get settings for the third Smart App in the list generated by "smartthings smartapps"',
			],
			[
				'$0 smartapps:settings 392bcb11-e251-44f3-b58b-17f93015f3aa',
				'get the settings of the Smart App with the given id',
			],
		])
		.epilog(buildEpilog({ command, apiDocs: ['getSmartAppSettings'] }))

const handler = async (argv: ArgumentsCamelCase<CommandArgs>): Promise<void> => {
	const command = await apiOrganizationCommand(argv)

	const id = await chooseSmartAppFn({ accountId: command.client.config.headers?.['X-ST-Organization'] })(
		command, argv.idOrIndex, { allowIndex: true },
	)

	await outputItem(
		command,
		{ buildTableOutput: appSettings => buildTableOutput(command.tableGenerator, appSettings) },
		() => command.client.smartapps.getSettings(id),
	)
}

const cmd: CommandModule<object, CommandArgs> = { command, describe, builder, handler }
export default cmd
