import { type ArgumentsCamelCase, type Argv, type CommandModule } from 'yargs'

import { apiCommand, apiCommandBuilder, type APICommandFlags, apiDocsURL } from '../../lib/command/api-command.js'
import { outputItem, outputItemBuilder, type OutputItemFlags } from '../../lib/command/output-item.js'
import { chooseApp, oauthTableFieldDefinitions } from '../../lib/command/util/apps-util.js'


export type CommandArgs = APICommandFlags & OutputItemFlags & {
	idOrIndex?: string
}

const command = 'apps:oauth [id-or-index]'

const describe = 'get OAuth information for an app'

const builder = (yargs: Argv): Argv<CommandArgs> =>
	outputItemBuilder(apiCommandBuilder(yargs))
		.positional('id-or-index', { describe: 'the app id or number from list', type: 'string' })
		.example([
			['$0 apps:oauth', 'prompt for an app and list OAuth information for it'],
			[
				'$0 apps:oauth 2',
				'list OAuth information for the second app in the list generated by "smartthings apps"',
			],
			[
				'$0 apps:oauth 392bcb11-e251-44f3-b58b-17f93015f3aa',
				'list OAuth information for the app with the given id',
			],
		])
		.epilog(apiDocsURL('getAppOauth'))

const handler = async (argv: ArgumentsCamelCase<CommandArgs>): Promise<void> => {
	const command = await apiCommand(argv)

	const id = await chooseApp(command, argv.idOrIndex, { allowIndex: true })
	await outputItem(
		command,
		{ tableFieldDefinitions: oauthTableFieldDefinitions },
		() => command.client.apps.getOauth(id),
	)
}

const cmd: CommandModule<object, CommandArgs> = { command, describe, builder, handler }
export default cmd
