const config = {
	preset: 'ts-jest',
	testMatch: [
		'**/__tests__/**/*.test.ts',
	],
	setupFilesAfterEnv: ['jest-extended/all'],
	collectCoverageFrom: ['src/**/*.ts'],
	coveragePathIgnorePatterns: [
		'/node_modules/',
		'/__tests__/',
		'/src/typings/',
		'/src/index.ts',
	],
	modulePathIgnorePatterns: [
		'<rootDir>/dist',
		'<rootDir>/lib',
	],
	clearMocks: true,
	reporters: [
		'default',
		'github-actions',
		'jest-html-reporters',
	],
	extensionsToTreatAsEsm: ['.ts'],
	moduleNameMapper: {
		// eslint-disable-next-line @typescript-eslint/naming-convention
		'^(\\.{1,2}/.*)\\.js$': '$1',
	},
	transform: {
		// '^.+\\.[tj]sx?$' to process js/ts with `ts-jest`
		// '^.+\\.m?[tj]sx?$' to process js/ts/mjs/mts with `ts-jest`
		// eslint-disable-next-line @typescript-eslint/naming-convention
		'^.+\\.tsx?$': [
			'ts-jest',
			{
				useESM: true,
				// TODO: remove when https://github.com/kulshekhar/ts-jest/issues/1967 is resolved
				// related flag in tsconfig as well
				isolatedModules: true,
			},
		],
	},
	testPathIgnorePatterns: [
		'./src/__tests__/commands/apps.test.ts',
		'./src/__tests__/commands/apps/authorize.test.ts',
		'./src/__tests__/commands/apps/create.test.ts',
		'./src/__tests__/commands/apps/delete.test.ts',
		'./src/__tests__/commands/apps/oauth.test.ts',
		'./src/__tests__/commands/apps/oauth/generate.test.ts',
		'./src/__tests__/commands/apps/oauth/update.test.ts',
		'./src/__tests__/commands/apps/register.test.ts',
		'./src/__tests__/commands/apps/settings.test.ts',
		'./src/__tests__/commands/apps/settings/update.test.ts',
		'./src/__tests__/commands/apps/update.test.ts',
		'./src/__tests__/commands/capabilities/translations.test.ts',
		'./src/__tests__/commands/config/reset.test.ts',
		'./src/__tests__/commands/devicepreferences/translations.test.ts',
		'./src/__tests__/commands/devicepreferences/translations/create.test.ts',
		'./src/__tests__/commands/devicepreferences/translations/update.test.ts',
		'./src/__tests__/commands/deviceprofiles.test.ts',
		'./src/__tests__/commands/devices.test.ts',
		'./src/__tests__/commands/devices/capability-status.test.ts',
		'./src/__tests__/commands/devices/commands.test.ts',
		'./src/__tests__/commands/devices/delete.test.ts',
		'./src/__tests__/commands/devices/history.test.ts',
		'./src/__tests__/commands/devices/update.test.ts',
		'./src/__tests__/commands/installedapps.test.ts',
		'./src/__tests__/commands/installedapps/delete.test.ts',
		'./src/__tests__/commands/installedapps/rename.test.ts',
		'./src/__tests__/commands/installedschema.test.ts',
		'./src/__tests__/commands/locations.test.ts',
		'./src/__tests__/commands/locations/create.test.ts',
		'./src/__tests__/commands/locations/delete.test.ts',
		'./src/__tests__/commands/locations/history.test.ts',
		'./src/__tests__/commands/locations/rooms.test.ts',
		'./src/__tests__/commands/locations/rooms/create.test.ts',
		'./src/__tests__/commands/locations/rooms/delete.test.ts',
		'./src/__tests__/commands/locations/rooms/update.test.ts',
		'./src/__tests__/commands/locations/update.test.ts',
		'./src/__tests__/commands/organizations.test.ts',
		'./src/__tests__/commands/presentation/device-config.test.ts',
		'./src/__tests__/commands/rules.test.ts',
		'./src/__tests__/commands/rules/create.test.ts',
		'./src/__tests__/commands/rules/delete.test.ts',
		'./src/__tests__/commands/rules/execute.test.ts',
		'./src/__tests__/commands/rules/update.test.ts',
		'./src/__tests__/commands/scenes.test.ts',
		'./src/__tests__/commands/scenes/execute.test.ts',
		'./src/__tests__/commands/schema.test.ts',
		'./src/__tests__/commands/schema/authorize.test.ts',
		'./src/__tests__/commands/schema/create.test.ts',
		'./src/__tests__/commands/schema/delete.test.ts',
		'./src/__tests__/commands/schema/regenerate.test.ts',
		'./src/__tests__/commands/schema/update.test.ts',
		'./src/__tests__/commands/virtualdevices.test.ts',
		'./src/__tests__/commands/virtualdevices/create-standard.test.ts',
		'./src/__tests__/commands/virtualdevices/create.test.ts',
		'./src/__tests__/commands/virtualdevices/delete.test.ts',
		'./src/__tests__/commands/virtualdevices/events.test.ts',
		'./src/__tests__/commands/virtualdevices/update.test.ts',
		'./src/__tests__/lib/commands/apps-util.test.ts',
		'./src/__tests__/lib/commands/capabilities-util.test.ts',
		'./src/__tests__/lib/commands/deviceprofiles-util.test.ts',
		'./src/__tests__/lib/commands/deviceprofiles/view-util.test.ts',
		'./src/__tests__/lib/commands/devices-util.test.ts',
		'./src/__tests__/lib/commands/history-util.test.ts',
		'./src/__tests__/lib/commands/installeddschema-util.test.ts',
		'./src/__tests__/lib/commands/locations/rooms-util.test.ts',
		'./src/__tests__/lib/commands/rules-util.test.ts',
		'./src/__tests__/lib/commands/scenes-util.test.ts',
		'./src/__tests__/lib/commands/virtualdevices-util.test.ts',
	],
}

module.exports = config
